/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LiferecorderSyncDialog.java
 *
 * Created on 13-Feb-2011, 10:08:13 PM
 */

package com.googlecode.eckoit.tray;

import com.googlecode.eckoit.events.LiferecorderSyncProcessMessage;
import com.googlecode.eckoit.events.ShowDashboardMessage;
import org.bushe.swing.event.EventBus;
import org.bushe.swing.event.EventSubscriber;

/**
 *
 * @author ryan
 */
public class LiferecorderSyncDialog extends javax.swing.JDialog {

    /** Creates new form LiferecorderSyncDialog */
    public LiferecorderSyncDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        stepProgess.setMinimum(0);
        stepProgess.setMaximum(100);
        EventBus.subscribeStrongly(ShowDashboardMessage.class, new EventSubscriber<ShowDashboardMessage>() {
            @Override
            public void onEvent(ShowDashboardMessage t) {
                dispose();
            }
        });
        EventBus.subscribeStrongly(LiferecorderSyncProcessMessage.class, new EventSubscriber<LiferecorderSyncProcessMessage>() {
            @Override
            public void onEvent(LiferecorderSyncProcessMessage t) {
                stepLabel.setText(t.getStep());
                stepProgess.setMaximum(t.getTotalSteps());
                stepProgess.setValue(t.getProgress());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        stepProgess = new javax.swing.JProgressBar();
        stepLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liferecorder Sync");

        jLabel1.setText("Liferecorder Sync - Please Keep Connected");

        stepLabel.setText("Copying Files");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(stepProgess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(stepLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepProgess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LiferecorderSyncDialog dialog = new LiferecorderSyncDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel stepLabel;
    private javax.swing.JProgressBar stepProgess;
    // End of variables declaration//GEN-END:variables

}
